[toolchain]
anchor_version = "0.32.1"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[programs.localnet]
friend_groups = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
# events = "<YOUR_EVENTS_PROGRAM_ID>"

[programs.devnet]
friend_groups = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
# events = "<YOUR_EVENTS_PROGRAM_ID>"

[programs.mainnet]
friend_groups = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
# events = "<YOUR_EVENTS_PROGRAM_ID>"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 20000

[scripts]
test = "npm run test:ts"