[toolchain]
anchor_version = "0.32.1"
solana_version = "2.2.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
friend_groups = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
events = "GHzeKGDCAsPzt2BMkXrS8y8azC4jDYec2SNuwd4tmZ9F"

[programs.localnet]
friend_groups = "A4hEysUGCcMWtuiWMCUZr8nw6mL8WDkTsKXjifTttCQJ"
events = "GHzeKGDCAsPzt2BMkXrS8y8azC4jDYec2SNuwd4tmZ9F"

[programs.mainnet]
friend_groups = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
events = "GHzeKGDCAsPzt2BMkXrS8y8azC4jDYec2SNuwd4tmZ9F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:ts"

[test]
startup_wait = 30000
shutdown_wait = 2000
upgradeable = false
